=== norsk-helsearkiv/avlxml/avlsup.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
  targetNamespace="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:avlmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
  xmlns:supmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
  elementFormDefault="qualified">

  <xs:import namespace="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
    schemaLocation="avlxml-mdk.xsd"/>
  <xs:import namespace="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
    schemaLocation="avlsup-mdk.xsd"/>

  <xs:element name="avlsup" type="supplerendeopplysninger"/>

  <xs:complexType name="supplerendeopplysninger">
    <xs:annotation>
      <xs:documentation>
        Supplerende opplysninger hentet fra elektronisk PAS, EPJ eller annet registratur
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="dokument" type="dokument"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="dokument">
    <xs:annotation>
      <xs:documentation>
        For hver pasient etableres det en fil med supplerende opplysninger per dokument. Hvert 
        dokument kobles til pasientjournalen ved hjelp av journalidentifikatoren som er benyttet 
        for pasienten.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="dokumentidentifikator" type="supmdk:dokumentidentifikator"/>
      <xs:element name="journalidentifikator" type="avlmdk:journalidentifikator"/>
      <xs:element name="filsti" type="supmdk:filsti"/>
      <xs:element name="dokumenttype" type="dokumenttype"/>
      <xs:element name="dokumentdato" type="supmdk:dokumentdato"/>
      <xs:element maxOccurs="unbounded" name="Organisasjon" type="Organisasjon"/>
      <xs:element minOccurs="0" name="episode" type="episode"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="diagnose" type="diagnose"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="prosedyre" type="prosedyre"/>
      <xs:element minOccurs="0" name="henvisningsperiode" type="henvisningsperiode"/>
      <xs:element name="behandlendeAvdeling" type="behandlendeAvdeling"/>
      <xs:element minOccurs="0" name="saksnummer" type="supmdk:saksnummer"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="dokumenttype">
    <xs:annotation>
      <xs:documentation>Dokumenttype</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="dokumenttypeKode" type="supmdk:dokumenttypeKode"/>
      <xs:element name="dokumenttypeTekst" type="supmdk:dokumenttypeTekst"/>
      <xs:element name="dokumenttypeKodeverk" type="supmdk:dokumenttypeKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Organisasjon">
    <xs:annotation>
      <xs:documentation>Informasjon om organisasjonen(e) som har lagt inn informasjon i dokumentet.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="organisasjonNummer" type="avlmdk:organisasjonsnummer"/>
      <xs:element name="organisasjonNavn" type="avlmdk:foretaksnavn"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="episode">
    <xs:annotation>
      <xs:documentation>Angis for dokumenter som er tilknyttet en episode.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="episodeId" type="supmdk:episodeID"/>
      <xs:element name="episodeStartdato" type="supmdk:episodeStartdato"/>
      <xs:element name="episodeSluttdato" type="supmdk:episodeStartdato"/>
      <xs:element name="omsorgsniva" type="omsorgsniva"/>
      <xs:element name="fagomrade" type="fagomrade"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="omsorgsniva">
    <xs:annotation>
      <xs:documentation>
        Omsorgsnivå på episoden. Omsorgsnivået angir om behandlingen har vært poliklinisk eller innleggelse.      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="omsorgsnivaKode" type="supmdk:omsorgsnivaKode"/>
      <xs:element name="omsorgsnivaKodetekst" type="supmdk:omsorgsnivaKodetekst"/>
      <xs:element name="omsorgsnivaKodeverk" type="supmdk:omsorgsnivaKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fagomrade">
    <xs:annotation>
      <xs:documentation>
        Fagområde på episoden
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="fagomradeKode" type="supmdk:fagomradeKode"/>
      <xs:element name="fagomradeKodetekst" type="supmdk:fagomradeKodetekst"/>
      <xs:element name="fagomradeKodeverk" type="supmdk:fagomradeKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="diagnose">
    <xs:annotation>
      <xs:documentation>Diagnosene som har blitt stilt i forbindelse med en episode angis for dokumenter som er knyttet til denne episoden.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="diagnosedato" type="avlmdk:diagnosedato"/>
      <xs:element name="diagnosekode" type="avlmdk:diagnosekode"/>
      <xs:element name="diagnosetekst" type="avlmdk:diagnosetekst"/>
      <xs:element name="diagnosekodeverk" type="avlmdk:diagnosekodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="prosedyre">
    <xs:annotation>
      <xs:documentation>Prosedyre(ne) som har blitt gjennomført i forbindelse med en episode angis for dokumenter som er knyttet til denne episoden.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="prosedyreKode" type="supmdk:prosedyreKode"/>
      <xs:element name="prosedyreKodetekst" type="supmdk:prosedyreKodetekst"/>
      <xs:element name="prosedyreKodeverk" type="supmdk:prosedyreKodeverk"/>
      <xs:element name="prosedyreDato" type="supmdk:prosedyreDato"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="henvisningsperiode">
    <xs:annotation>
      <xs:documentation>For dokumenter knyttet til en episode skal henvisningsperiode angis.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="henvisningsperiodeId" type="supmdk:henvisningsperiodeId"/>
      <xs:element name="henvisningsperiodeStartdato" type="supmdk:henvisningsperiodeStartdato"/>
      <xs:element name="henvisningsperiodeSluttdato" type="supmdk:henvisningsperiodeSluttdato"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="behandlendeAvdeling">
    <xs:annotation>
      <xs:documentation>Informasjon om avdelingen som behandlet pasienten.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="behandlendeAvdelingReshId" type="supmdk:behandlendeAvdelingReshID"/>
      <xs:element name="behandlendeAvdelingNavn" type="supmdk:behandlendeAvdelingNavn"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== norsk-helsearkiv/avlxml/avlsup-example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<avlsup xmlns:avlmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
 xmlns:supmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
 xmlns="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.arkivverket.no/standarder/nha/avlxml/avlsup file:/C:/Users/areant/work/avlxml/avlsup.xsd">
    <dokument>
        <dokumentidentifikator>dokumentidentifikator0</dokumentidentifikator>
        <journalidentifikator>journalidentifikator0</journalidentifikator>
        <filsti>filsti0</filsti>
        <dokumenttype>
            <dokumenttypeKode>dokumenttypeKode0</dokumenttypeKode>
            <dokumenttypeTekst>dokumenttypeTekst0</dokumenttypeTekst>
            <dokumenttypeKodeverk>dokumenttypeKodeverk0</dokumenttypeKodeverk>
        </dokumenttype>
        <dokumentdato>1800</dokumentdato>
        <Organisasjon>
            <organisasjonNummer>000000000</organisasjonNummer>
            <organisasjonNavn>organisasjonNavn0</organisasjonNavn>
        </Organisasjon>
        <Organisasjon>
            <organisasjonNummer>000000000</organisasjonNummer>
            <organisasjonNavn>organisasjonNavn1</organisasjonNavn>
        </Organisasjon>
        <episode>
            <episodeId>episodeId0</episodeId>
            <episodeStartdato>1800</episodeStartdato>
            <episodeSluttdato>1800</episodeSluttdato>
            <omsorgsniva>
                <omsorgsnivaKode>omsorgsnivaKode0</omsorgsnivaKode>
                <omsorgsnivaKodetekst>omsorgsnivaKodetekst0</omsorgsnivaKodetekst>
                <omsorgsnivaKodeverk>omsorgsnivaKodeverk0</omsorgsnivaKodeverk>
            </omsorgsniva>
            <fagomrade>
                <fagomradeKode>fagomradeKode0</fagomradeKode>
                <fagomradeKodetekst>fagomradeKodetekst0</fagomradeKodetekst>
                <fagomradeKodeverk>fagomradeKodeverk0</fagomradeKodeverk>
            </fagomrade>
        </episode>
        <diagnose>
            <diagnosedato>1800</diagnosedato>
            <diagnosekode>diagnosekode0</diagnosekode>
            <diagnosetekst>diagnosetekst0</diagnosetekst>
            <diagnosekodeverk>0</diagnosekodeverk>
        </diagnose>
        <diagnose>
            <diagnosedato>1800</diagnosedato>
            <diagnosekode>diagnosekode1</diagnosekode>
            <diagnosetekst>diagnosetekst1</diagnosetekst>
            <diagnosekodeverk>0</diagnosekodeverk>
        </diagnose>
        <prosedyre>
            <prosedyreKode>prosedyreKode0</prosedyreKode>
            <prosedyreKodetekst>prosedyreKodetekst0</prosedyreKodetekst>
            <prosedyreKodeverk>prosedyreKodeverk0</prosedyreKodeverk>
            <prosedyreDato>1800</prosedyreDato>
        </prosedyre>
        <prosedyre>
            <prosedyreKode>prosedyreKode1</prosedyreKode>
            <prosedyreKodetekst>prosedyreKodetekst1</prosedyreKodetekst>
            <prosedyreKodeverk>prosedyreKodeverk1</prosedyreKodeverk>
            <prosedyreDato>1800</prosedyreDato>
        </prosedyre>
        <henvisningsperiode>
            <henvisningsperiodeId>henvisningsperiodeId0</henvisningsperiodeId>
            <henvisningspeirodeStartdato>1800</henvisningspeirodeStartdato>
            <henvisningspeirodeSluttdato>1800</henvisningspeirodeSluttdato>
        </henvisningsperiode>
        <behandlendeAvdeling>
            <behandlendeAvdelingReshId>behandlendeAvdelingReshId0</behandlendeAvdelingReshId>
            <behandlendeavdelingNavn>behandlendeavdelingNavn0</behandlendeavdelingNavn>
        </behandlendeAvdeling>
        <saksnummer>saksnummer0</saksnummer>
    </dokument>
    <dokument>
        <dokumentidentifikator>dokumentidentifikator1</dokumentidentifikator>
        <journalidentifikator>journalidentifikator1</journalidentifikator>
        <filsti>filsti1</filsti>
        <dokumenttype>
            <dokumenttypeKode>dokumenttypeKode1</dokumenttypeKode>
            <dokumenttypeTekst>dokumenttypeTekst1</dokumenttypeTekst>
            <dokumenttypeKodeverk>dokumenttypeKodeverk1</dokumenttypeKodeverk>
        </dokumenttype>
        <dokumentdato>1800</dokumentdato>
        <Organisasjon>
            <organisasjonNummer>000000000</organisasjonNummer>
            <organisasjonNavn>organisasjonNavn2</organisasjonNavn>
        </Organisasjon>
        <Organisasjon>
            <organisasjonNummer>000000000</organisasjonNummer>
            <organisasjonNavn>organisasjonNavn3</organisasjonNavn>
        </Organisasjon>
        <episode>
            <episodeId>episodeId1</episodeId>
            <episodeStartdato>1800</episodeStartdato>
            <episodeSluttdato>1800</episodeSluttdato>
            <omsorgsniva>
                <omsorgsnivaKode>omsorgsnivaKode1</omsorgsnivaKode>
                <omsorgsnivaKodetekst>omsorgsnivaKodetekst1</omsorgsnivaKodetekst>
                <omsorgsnivaKodeverk>omsorgsnivaKodeverk1</omsorgsnivaKodeverk>
            </omsorgsniva>
            <fagomrade>
                <fagomradeKode>fagomradeKode1</fagomradeKode>
                <fagomradeKodetekst>fagomradeKodetekst1</fagomradeKodetekst>
                <fagomradeKodeverk>fagomradeKodeverk1</fagomradeKodeverk>
            </fagomrade>
        </episode>
        <diagnose>
            <diagnosedato>1800</diagnosedato>
            <diagnosekode>diagnosekode2</diagnosekode>
            <diagnosetekst>diagnosetekst2</diagnosetekst>
            <diagnosekodeverk>0</diagnosekodeverk>
        </diagnose>
        <diagnose>
            <diagnosedato>1800</diagnosedato>
            <diagnosekode>diagnosekode3</diagnosekode>
            <diagnosetekst>diagnosetekst3</diagnosetekst>
            <diagnosekodeverk>0</diagnosekodeverk>
        </diagnose>
        <prosedyre>
            <prosedyreKode>prosedyreKode2</prosedyreKode>
            <prosedyreKodetekst>prosedyreKodetekst2</prosedyreKodetekst>
            <prosedyreKodeverk>prosedyreKodeverk2</prosedyreKodeverk>
            <prosedyreDato>1800</prosedyreDato>
        </prosedyre>
        <prosedyre>
            <prosedyreKode>prosedyreKode3</prosedyreKode>
            <prosedyreKodetekst>prosedyreKodetekst3</prosedyreKodetekst>
            <prosedyreKodeverk>prosedyreKodeverk3</prosedyreKodeverk>
            <prosedyreDato>1800</prosedyreDato>
        </prosedyre>
        <henvisningsperiode>
            <henvisningsperiodeId>henvisningsperiodeId1</henvisningsperiodeId>
            <henvisningspeirodeStartdato>1800</henvisningspeirodeStartdato>
            <henvisningspeirodeSluttdato>1800</henvisningspeirodeSluttdato>
        </henvisningsperiode>
        <behandlendeAvdeling>
            <behandlendeAvdelingReshId>behandlendeAvdelingReshId1</behandlendeAvdelingReshId>
            <behandlendeavdelingNavn>behandlendeavdelingNavn1</behandlendeavdelingNavn>
        </behandlendeAvdeling>
        <saksnummer>saksnummer1</saksnummer>
    </dokument>
</avlsup>

=== norsk-helsearkiv/avlxml/dokumentasjon/avlsup-example-avlxml-v3-draft-alt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<avlsup xmlns:avlmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
 xmlns:supmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
 xmlns="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.arkivverket.no/standarder/nha/avlxml/avlsup file:/C:/Users/areant/work/avlxml/avlsup.xsd">
    <dokument>
        <dokumentidentifikator>H78JTcx65B._2y7U</dokumentidentifikator>
        <journalidentifikator>S6eXzRVtdz1UPf2.AcA</journalidentifikator>
        <filsti>zZC0srmHso65t42tvXqA1YmI</filsti>
        <dokumenttype>
            <dokumenttypeKode>OYlwcC7ZHAGA4Szgb-VSuK_7X2</dokumenttypeKode>
            <dokumenttypeTekst>rI.MxjapjC</dokumenttypeTekst>
            <dokumenttypeKodeverk>ZN</dokumenttypeKodeverk>
        </dokumenttype>
        <dokumentdato>20721025</dokumentdato>
        <Organisasjon>
            <organisasjonNummer>633917991</organisasjonNummer>
            <organisasjonNavn>CC0TX9T-ogmtOxP8xud-HJpAvL</organisasjonNavn>
        </Organisasjon>
        <Organisasjon>
            <organisasjonNummer>858468311</organisasjonNummer>
            <organisasjonNavn>E3aJCjdgGqS</organisasjonNavn>
        </Organisasjon>
        <episode>
            <episodeId>EhDMcxjgfE</episodeId>
            <episodeStartdato>1930</episodeStartdato>
            <episodeSluttdato>1924-07</episodeSluttdato>
            <omsorgsniva>
                <omsorgsnivaKode>mlHNab956X6_YWA2</omsorgsnivaKode>
                <omsorgsnivaKodetekst>w1Vt_hl</omsorgsnivaKodetekst>
                <omsorgsnivaKodeverk>FwxsDtmrPKuRImK6DvrKSpUFgy</omsorgsnivaKodeverk>
            </omsorgsniva>
            <fagomrade>
                <fagomradeKode>lSuAJZ8dEGH_an49U7-cuq</fagomradeKode>
                <fagomradeKodetekst>GHWo7uTNPmyV</fagomradeKodetekst>
                <fagomradeKodeverk>y5AwV52v9j7fYWPkVNNAZ</fagomradeKodeverk>
            </fagomrade>
        </episode>
        <diagnose>
            <diagnosedato>18411209</diagnosedato>
            <diagnosekode>OulowQBVb2KSEg</diagnosekode>
            <diagnosetekst>u54</diagnosetekst>
            <diagnosekodeverk>0</diagnosekodeverk>
        </diagnose>
        <diagnose>
            <diagnosedato>20880130</diagnosedato>
            <diagnosekode>LRyOVixMaTjkwQGMKQX</diagnosekode>
            <diagnosetekst>seCiN</diagnosetekst>
            <diagnosekodeverk>7a5o7</diagnosekodeverk>
        </diagnose>
        <prosedyre>
            <prosedyreKode>DQxZz4eSWEkhdVuQ</prosedyreKode>
            <prosedyreKodetekst>zogGDCQv8.SR_</prosedyreKodetekst>
            <prosedyreKodeverk>E8O8R4</prosedyreKodeverk>
            <prosedyreDato>2030-10-03</prosedyreDato>
        </prosedyre>
        <prosedyre>
            <prosedyreKode>IJa31pOClW</prosedyreKode>
            <prosedyreKodetekst>z8CAbhFLGkuEV</prosedyreKodetekst>
            <prosedyreKodeverk>oTS_MzmMKUzWf9z7-0EKKQ.6rji.Ma</prosedyreKodeverk>
            <prosedyreDato>20750910</prosedyreDato>
        </prosedyre>
        <henvisningsperiode>
            <henvisningsperiodeId>KQZBBC-_</henvisningsperiodeId>
            <henvisningspeirodeStartdato>2011</henvisningspeirodeStartdato>
            <henvisningspeirodeSluttdato>20850422</henvisningspeirodeSluttdato>
        </henvisningsperiode>
        <behandlendeAvdeling>
            <behandlendeAvdelingReshId>vZVBhQnT1eDWTG6UUme</behandlendeAvdelingReshId>
            <behandlendeavdelingNavn>uE6TPUUne3qk</behandlendeavdelingNavn>
        </behandlendeAvdeling>
        <saksnummer>DjZWjZHcf</saksnummer>
    </dokument>
    <dokument>
        <dokumentidentifikator>chqTsT</dokumentidentifikator>
        <journalidentifikator>cGTNWz3aJnIOUgrDN</journalidentifikator>
        <filsti>gH9QClBBEYHNAf</filsti>
        <dokumenttype>
            <dokumenttypeKode>M961Q</dokumenttypeKode>
            <dokumenttypeTekst>YxdB.388ibJWl-D03L</dokumenttypeTekst>
            <dokumenttypeKodeverk>ChWm</dokumenttypeKodeverk>
        </dokumenttype>
        <dokumentdato>2072-06</dokumentdato>
        <Organisasjon>
            <organisasjonNummer>217463014</organisasjonNummer>
            <organisasjonNavn>s68JW2vY_fwly</organisasjonNavn>
        </Organisasjon>
        <Organisasjon>
            <organisasjonNummer>962361855</organisasjonNummer>
            <organisasjonNavn>zqWoEFPquxHv</organisasjonNavn>
        </Organisasjon>
        <episode>
            <episodeId>_Neh-4bacl4</episodeId>
            <episodeStartdato>19140925</episodeStartdato>
            <episodeSluttdato>20111124</episodeSluttdato>
            <omsorgsniva>
                <omsorgsnivaKode>hg1PsaS3NDV.RnhJ</omsorgsnivaKode>
                <omsorgsnivaKodetekst>LC7LdhgQsR</omsorgsnivaKodetekst>
                <omsorgsnivaKodeverk>GS9RAFO2GHi1KW4Bu378Eczh</omsorgsnivaKodeverk>
            </omsorgsniva>
            <fagomrade>
                <fagomradeKode>ums6fXfSTlKKm</fagomradeKode>
                <fagomradeKodetekst>u8eXKABquG1ueXwEspUy77TolC9</fagomradeKodetekst>
                <fagomradeKodeverk>IL7ejx9xZ</fagomradeKodeverk>
            </fagomrade>
        </episode>
        <diagnose>
            <diagnosedato>20660308</diagnosedato>
            <diagnosekode>avgGbtZroAc</diagnosekode>
            <diagnosetekst>rZ2FJAF</diagnosetekst>
            <diagnosekodeverk>186a3</diagnosekodeverk>
        </diagnose>
        <diagnose>
            <diagnosedato>2002</diagnosedato>
            <diagnosekode>Qr6B9</diagnosekode>
            <diagnosetekst>xea8IHWmeeoP</diagnosetekst>
            <diagnosekodeverk>0j9a4x2</diagnosekodeverk>
        </diagnose>
        <prosedyre>
            <prosedyreKode>sK3MnlIG_yuns-t</prosedyreKode>
            <prosedyreKodetekst>Jpf-IXWjH7R</prosedyreKodetekst>
            <prosedyreKodeverk>n333IYvq1JUdliNcjvMUMAFQsTQ</prosedyreKodeverk>
            <prosedyreDato>2035</prosedyreDato>
        </prosedyre>
        <prosedyre>
            <prosedyreKode>ClIzUyfG2JNrTLGMh</prosedyreKode>
            <prosedyreKodetekst>HTfpbI65</prosedyreKodetekst>
            <prosedyreKodeverk>kkl1kO-FHRFbR3X4EtP</prosedyreKodeverk>
            <prosedyreDato>19060830</prosedyreDato>
        </prosedyre>
        <henvisningsperiode>
            <henvisningsperiodeId>RyGU-UqsQc2UiGbRS6vV</henvisningsperiodeId>
            <henvisningspeirodeStartdato>20390530</henvisningspeirodeStartdato>
            <henvisningspeirodeSluttdato>1906</henvisningspeirodeSluttdato>
        </henvisningsperiode>
        <behandlendeAvdeling>
            <behandlendeAvdelingReshId>A81qfgX.8b</behandlendeAvdelingReshId>
            <behandlendeavdelingNavn>_B8bl4n47s4dKVG_qn1</behandlendeavdelingNavn>
        </behandlendeAvdeling>
        <saksnummer>HauJ.TUVUWw2YdO1.m</saksnummer>
    </dokument>
</avlsup>
